[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel",
  "python310Packages.cython",
  "ffmpeg",
  "libsndfile",
  "gcc",
  "libffi",
  "pkg-config",
  "postgresql",
  "blas",
  "lapack",
  "bash"

]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install numpy scipy",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput",
  "/opt/venv/bin/python manage.py migrate --noinput"
]

[start]
cmd = "/opt/venv/bin/gunicorn --bind 0.0.0.0:$PORT --workers 3 --timeout 120 core.wsgi:application"

[variables]
PYTHONUNBUFFERED = "1"
VIRTUAL_ENV = "/opt/venv"
PATH = "/opt/venv/bin:$PATH"