# Generated by Django 5.2.5 on 2025-09-03 01:35

import django.db.models.deletion
import stations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default=stations.models.get_default_station_image, null=True, upload_to='stations/')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_account', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=900, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, default=0.0, max_digits=50, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=20, default=0.0, max_digits=50, null=True)),
                ('avg_detection_confidence', models.DecimalField(blank=True, decimal_places=20, default=0.0, max_digits=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('onboarding_step', models.CharField(choices=[('profile', 'Complete Profile'), ('staff', 'Staff'), ('payment', 'Add Payment Info')], default='profile', max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('staff_completed', models.BooleanField(default=False)),
                ('report_completed', models.BooleanField(default=False)),
                ('payment_info_added', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_programs', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Producer', 'Producer'), ('Presenter', 'Presenter'), ('Dj', 'Dj')], max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_programs', to='stations.stationprogram')),
            ],
        ),
        migrations.CreateModel(
            name='StationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('Producer', 'Producer'), ('Presenter', 'Presenter'), ('Dj', 'Dj')], max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_staff', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationStreamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='stations.station')),
            ],
        ),
    ]
