# Generated by Django 5.2.5 on 2025-09-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('fan', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('avg_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_station', to='stations.station')),
                ('station_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_station_program', to='stations.stationprogram')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_track', to='artists.track')),
            ],
        ),
        migrations.CreateModel(
            name='FailedPlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('will_retry', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_monitor.matchcache')),
            ],
        ),
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Radio', 'Radio'), ('Streaming', 'Streaming')], max_length=50)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('royalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_playlog', to='stations.station')),
                ('station_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_program_playlog', to='stations.stationprogram')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlog', to='artists.track')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_status', models.CharField(blank=True, choices=[('Flagged', 'Flagged'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Resolving', 'Resolving'), ('Review', 'Review'), ('Resolved', 'Resolved')], max_length=100, null=True)),
                ('dispute_comments', models.TextField(blank=True, null=True)),
                ('resolve_comments', models.TextField(blank=True, null=True)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolving_time', models.DateTimeField(blank=True, null=True)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DurationField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_playlog', to='music_monitor.playlog')),
            ],
        ),
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('royalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('dispute_status', models.CharField(blank=True, choices=[('Flagged', 'Flagged'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Resolving', 'Resolving'), ('Review', 'Review'), ('Resolved', 'Resolved')], max_length=100, null=True)),
                ('disput_comments', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_playlog', to='fan.fan')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_streamlog', to='artists.track')),
            ],
        ),
    ]
