# Generated by Django 4.2 on 2025-09-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherprofile',
            name='momo_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
